#!/usr/bin/env bash
# Dsiplays "Best School" 10 times,
# but "Hi" before the last time

count=1
while [ $count -le 10 ]
do
    if [ $count -eq 10 ]
    then
        echo "Hi"
    fi
    echo "Best School"
    (( count++ ))
done
